apiVersion: v1
kind: PersistentVolume
metadata:
  name: lsadf-api-volume
  labels:
    type: local
    app: lsadf-api
spec:
  storageClassName: fast
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/lsadf_api_data