server:
  port: ${LSADF_API_PORT}

db:
  url: ${DB_URL_DOCKER}

logging:
  config: file:logback-docker.xml

cache:
  redis:
    host: ${REDIS_HOST_DOCKER}
    port: ${REDIS_PORT_DOCKER}

keycloak:
  url: ${KEYCLOAK_URI_DOCKER}
  admin-url: ${KEYCLOAK_ADMIN_URI_DOCKER}
  issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}