apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsdaf-backend
  labels:
    app: lsdaf-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsdaf-backend
  template:
    metadata:
      labels:
        app: lsdaf-backend
    spec:
      containers:
      - name: lsdaf-backend
        image: lsdaf-backend
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: lsdaf-env-config
        - secretRef:
            name: lsdaf-secrets
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10