apiVersion: v1
kind: Secret
metadata:
  name: lsdaf-secrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin  # Replace with your actual admin username
  KEYCLOAK_ADMIN_PASSWORD: admin  # Replace with your actual admin password
  DB_URL_DOCKER: jdbc:postgresql://postgres:5432/lsadf?user=lsadf&password=lsadf
  REDIS_HOST_DOCKER: redis
  REDIS_PORT_DOCKER: "6379"
  KEYCLOAK_ADMIN_URI_DOCKER: http://keycloak:8081
  KEYCLOAK_URI_DOCKER: http://keycloak:8081
