FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY lsadf_api/target/*.jar app.jar
COPY ./docker/startup-dev.sh startup.sh
COPY lsadf_api/src/main/resources/logback-docker.xml logback-docker.xml

ENTRYPOINT ["./startup.sh"]