{{ if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.11
          envFrom:
            - secretRef:
                name: pgadmin-secret
          env:
            - name: PGADMIN_LISTEN_PORT
              value: "80"
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
{{ end }}