{{ if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.0-alpine
          command: [ "/bin/sh" ]
          args: [ "-c", "redis-server --daemonize yes --requirepass $$REDIS_PASSWORD && redis-cli -a $$REDIS_PASSWORD config set notify-keyspace-events KEA && sleep infinity" ]
          envFrom:
            - secretRef:
                name: redis-secret
          ports:
            - containerPort: {{ .Values.REDIS_PORT }}
              name: http
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
{{ end }}